// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: x/pb/v1/service.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenFGAXService_Tx_FullMethodName = "/linka.cloud.openfga.x.pb.v1.OpenFGAXService/Tx"
)

// OpenFGAXServiceClient is the client API for OpenFGAXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenFGAXServiceClient interface {
	Tx(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TxRequest, TxResponse], error)
}

type openFGAXServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenFGAXServiceClient(cc grpc.ClientConnInterface) OpenFGAXServiceClient {
	return &openFGAXServiceClient{cc}
}

func (c *openFGAXServiceClient) Tx(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TxRequest, TxResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OpenFGAXService_ServiceDesc.Streams[0], OpenFGAXService_Tx_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TxRequest, TxResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpenFGAXService_TxClient = grpc.BidiStreamingClient[TxRequest, TxResponse]

// OpenFGAXServiceServer is the server API for OpenFGAXService service.
// All implementations must embed UnimplementedOpenFGAXServiceServer
// for forward compatibility.
type OpenFGAXServiceServer interface {
	Tx(grpc.BidiStreamingServer[TxRequest, TxResponse]) error
	mustEmbedUnimplementedOpenFGAXServiceServer()
}

// UnimplementedOpenFGAXServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenFGAXServiceServer struct{}

func (UnimplementedOpenFGAXServiceServer) Tx(grpc.BidiStreamingServer[TxRequest, TxResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Tx not implemented")
}
func (UnimplementedOpenFGAXServiceServer) mustEmbedUnimplementedOpenFGAXServiceServer() {}
func (UnimplementedOpenFGAXServiceServer) testEmbeddedByValue()                         {}

// UnsafeOpenFGAXServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenFGAXServiceServer will
// result in compilation errors.
type UnsafeOpenFGAXServiceServer interface {
	mustEmbedUnimplementedOpenFGAXServiceServer()
}

func RegisterOpenFGAXServiceServer(s grpc.ServiceRegistrar, srv OpenFGAXServiceServer) {
	// If the following call pancis, it indicates UnimplementedOpenFGAXServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenFGAXService_ServiceDesc, srv)
}

func _OpenFGAXService_Tx_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OpenFGAXServiceServer).Tx(&grpc.GenericServerStream[TxRequest, TxResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpenFGAXService_TxServer = grpc.BidiStreamingServer[TxRequest, TxResponse]

// OpenFGAXService_ServiceDesc is the grpc.ServiceDesc for OpenFGAXService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenFGAXService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "linka.cloud.openfga.x.pb.v1.OpenFGAXService",
	HandlerType: (*OpenFGAXServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Tx",
			Handler:       _OpenFGAXService_Tx_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "x/pb/v1/service.proto",
}
